sudo: required
services:
  - docker

before_install:
  - docker build -f -t ramanwalwynvenu/docker-react Dockerfile.dev .

script:
  - docker run ramanwalwynvenu/docker-react npm run test -- --coverage
