sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ramanwalwynvenu/docker-react .

script:
  - docker run ramanwalwynvenu/docker-react npm run test -- --coverage
